
services: 
  postgres_db:
    image: postgres:16
    command:
      - "postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
        #healthcheck - Проверка состояния/работоспособности
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5432:5432"
  
  whodb:
    image: clidey/whodb
    ports:
      - "8080:8080"